export const ELEMENTS = {
    sessaoComprar: '#primary-menu > .menu-item-629 > a',
    barraDeBusca: '.search > .tbay-search-form > .form-ajax-search > .form-group > .input-group > .tbay-search',
    botaoProcurar: '.search > .tbay-search-form > .form-ajax-search > .form-group > .input-group > .button-group > .button-search',
    tamanhoDoProduto: '.button-variable-item-',
    corDoProduto: '.button-variable-item-',
    selecionarTamanhoXs: '.button-variable-item-XS',
    selecionarTamanho32: '.button-variable-item-32',
    selecionarCorAzul: '.button-variable-item-Blue',
    selecionarCorCinza: '.button-variable-item-Gray',
    selecionarCorPreta: '.button-variable-item-Black',
    adicionarAoCarrinho: '.single_add_to_cart_button',
    mensagemDeValidacao: '.woocommerce-message',
    verCarrinho: '.woocommerce-message > .button',
    concluirCompra: '.checkout-button',
    primeiroNome: '#billing_first_name',
    sobreNome: '#billing_last_name',
    listaDePaises: '#select2-billing_country-container',
    paises: '.select2-results__options',
    brasil: '#select2-billing_country-container',
    endereco: '#billing_address_1',
    cidade: '#billing_city',
    listaDeEstados: '#select2-billing_state-container',
    estados: '.select2-results__options',
    cep: '#billing_postcode',
    numeroTelefone: '#billing_phone',
    email: '#billing_email',
    pagamentoNaEntrega: '.wc_payment_method.payment_method_cod',
    termos: '#terms',
    finalizarCompra: '#place_order',
    pedidoConcluido: '.woocommerce-notice',



}